### ISSUE TITLE
Installation errors/problems

### ISSUE THREAD

**Issue by desmodus1984** [UDC-GAC/ParRADMeth#1]
Hi,

I have methylation data that I wanted to try with ParRADMeth, and I got some installation errors:
I cloned the directory with git clone, and then entered the app directory,

When I ran "make" it failed:

[juaguila@v001 ParRADMeth]$ make
make[1]: Entering directory `/home/juaguila/appz/ParRADMeth/src'
make[2]: Entering directory `/home/juaguila/appz/ParRADMeth/src/radmeth'
g++ -Wall -fmessage-length=50 -std=c++11 -O2 -c -o regression.o regression.cpp -I/home/juaguila/appz/ParRADMeth/src/smithlab_cpp -I../common
make[2]: g++: Command not found
make[2]: *** [regression.o] Error 127
make[2]: Leaving directory `/home/juaguila/appz/ParRADMeth/src/radmeth'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/juaguila/appz/ParRADMeth/src'
make: *** [all] Error 2

Then, since it needs GCC compiler I activated the GCC module of the HPC, 

[juaguila@v001 ParRADMeth]$ module load gcc-13.2.0-gcc-12.1.0 
and ran again make, and it failed.
Then, it needed GSL, and I activated GSL, and it failed:
[juaguila@u05 ParRADMeth]$ module load gsl-2.5-gcc-8.2.0-zi2ov24 

Then, it need MPI and it failed:
[juaguila@u05 ParRADMeth]$ module load mpich-3.2.1-gcc-8.2.0-7f6s2be 
[juaguila@u05 ParRADMeth]$ module load openmpi-4.1.5-gcc-12.1.0 

[juaguila@u05 ParRADMeth]$ make
make[1]: Entering directory `/home/juaguila/appz/ParRADMeth/src'
make[2]: Entering directory `/home/juaguila/appz/ParRADMeth/src/radmeth'
mpic++ -Wall -fmessage-length=50 -std=c++11 -O2 -fopenmp -o ParRADMeth ParRADMeth.cpp regression.o combine_pvals.o merge.o /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/smithlab_os.o /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/smithlab_utils.o /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/GenomicRegion.o /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/OptionParser.o ../common/MethpipeFiles.o -I/home/juaguila/appz/ParRADMeth/src/smithlab_cpp -I../common -lgsl -lgslcblas
/usr/bin/ld: regression.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: combine_pvals.o: relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: merge.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/smithlab_os.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/smithlab_utils.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/GenomicRegion.o: relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/juaguila/appz/ParRADMeth/src/smithlab_cpp/OptionParser.o: relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ../common/MethpipeFiles.o: relocation R_X86_64_32S against symbol `_ZNSs4_Rep20_S_empty_rep_storageE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/tmp/ccVdATC3.o: In function `main':
ParRADMeth.cpp:(.text.startup+0x93): undefined reference to `strip_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ParRADMeth.cpp:(.text.startup+0x24a): undefined reference to `OptionParser::OptionParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ParRADMeth.cpp:(.text.startup+0x301): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
ParRADMeth.cpp:(.text.startup+0x377): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool&)'
ParRADMeth.cpp:(.text.startup+0x3f3): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
ParRADMeth.cpp:(.text.startup+0x45e): undefined reference to `OptionParser::parse(int, char const**, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
ParRADMeth.cpp:(.text.startup+0x497): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x4cb): undefined reference to `OptionParser::about_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0xb87): undefined reference to `OptionParser::OptionParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ParRADMeth.cpp:(.text.startup+0xc1c): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
ParRADMeth.cpp:(.text.startup+0xc92): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, double&)'
ParRADMeth.cpp:(.text.startup+0xcfd): undefined reference to `OptionParser::parse(int, char const**, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
ParRADMeth.cpp:(.text.startup+0xd60): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0xdf7): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0xe55): undefined reference to `OptionParser::option_missing_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0xeb3): undefined reference to `OptionParser::about_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x21b8): undefined reference to `OptionParser::OptionParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ParRADMeth.cpp:(.text.startup+0x2265): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
ParRADMeth.cpp:(.text.startup+0x22db): undefined reference to `OptionParser::add_opt(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)'
ParRADMeth.cpp:(.text.startup+0x2347): undefined reference to `OptionParser::parse(int, char const**, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)'
ParRADMeth.cpp:(.text.startup+0x23b3): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x24ba): undefined reference to `OptionParser::option_missing_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x24f4): undefined reference to `OptionParser::about_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x252e): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x2568): undefined reference to `OptionParser::help_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x2717): undefined reference to `BinForDistance::BinForDistance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
ParRADMeth.cpp:(.text.startup+0x2bda): undefined reference to `OptionParser::about_message[abi:cxx11]() const'
ParRADMeth.cpp:(.text.startup+0x2c19): undefined reference to `OptionParser::option_missing_message[abi:cxx11]() const'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [ParRADMeth] Error 1
make[2]: Leaving directory `/home/juaguila/appz/ParRADMeth/src/radmeth'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/juaguila/appz/ParRADMeth/src'
make: *** [all] Error 2

Could you please tell what might be causing this?

Thanks;

**Comment by afdezfraga** [comment]
Hi @desmodus1984 .

**Comment by afdezfraga** [comment]
Hi @desmodus1984 .

I was not fully able to reproduce your error. 
However, a similar one happens to me. When I initially run `make`  without all the required modules loaded  and then I load all the modules and re-run `make` again the process keeps failing. 

To solve it, with all the required modules loaded run `make clean` and then run `make` again.
